/**
 * Canonical PostgreSQL table names for the externally managed healthcare database.
 *
 * These constants do not create or alter database objects. They are safe to use
 * as fixed SQL identifiers; user data must always be passed as parameters.
 */
export const TABLES = {
  identity: {
    users: 'identity.users',
    roles: 'identity.roles',
    permissions: 'identity.permissions',
    otp_challenges: 'identity.otp_challenges',
    api_clients: 'identity.api_clients',
    user_roles: 'identity.user_roles',
    role_permissions: 'identity.role_permissions',
    sessions: 'identity.sessions',
    mfa_factors: 'identity.mfa_factors',
    trusted_devices: 'identity.trusted_devices',
    login_attempts: 'identity.login_attempts',
    password_history: 'identity.password_history',
    api_client_secrets: 'identity.api_client_secrets',
    user_profiles: 'identity.user_profiles',
  },
  organization: {
    organizations: 'organization.organizations',
    locations: 'organization.locations',
    departments: 'organization.departments',
    bank_accounts: 'organization.bank_accounts',
    memberships: 'organization.memberships',
    licenses: 'organization.licenses',
  },
  customer: {
    family_members: 'customer.family_members',
    addresses: 'customer.addresses',
    consents: 'customer.consents',
    preferences: 'customer.preferences',
    wishlists: 'customer.wishlists',
    profiles: 'customer.profiles',
    consent_events: 'customer.consent_events',
    wishlist_items: 'customer.wishlist_items',
  },
  catalog: {
    categories: 'catalog.categories',
    salts: 'catalog.salts',
    dosage_forms: 'catalog.dosage_forms',
    units_of_measure: 'catalog.units_of_measure',
    manufacturers: 'catalog.manufacturers',
    substitution_groups: 'catalog.substitution_groups',
    brands: 'catalog.brands',
    products: 'catalog.products',
    product_variants: 'catalog.product_variants',
    product_salts: 'catalog.product_salts',
    product_attributes: 'catalog.product_attributes',
    product_relationships: 'catalog.product_relationships',
    product_regulatory: 'catalog.product_regulatory',
    product_content: 'catalog.product_content',
    substitution_group_products: 'catalog.substitution_group_products',
    product_identifiers: 'catalog.product_identifiers',
    product_media: 'catalog.product_media',
  },
  clinical: {
    practitioner_profiles: 'clinical.practitioner_profiles',
    practitioner_organizations: 'clinical.practitioner_organizations',
    patient_profiles: 'clinical.patient_profiles',
    patient_allergies: 'clinical.patient_allergies',
    patient_conditions: 'clinical.patient_conditions',
    care_episodes: 'clinical.care_episodes',
    patient_medications: 'clinical.patient_medications',
    consultations: 'clinical.consultations',
    diagnoses: 'clinical.diagnoses',
    observations: 'clinical.observations',
    prescriptions: 'clinical.prescriptions',
    prescription_documents: 'clinical.prescription_documents',
    prescription_items: 'clinical.prescription_items',
    prescription_access_logs: 'clinical.prescription_access_logs',
  },
  appointment: {
    service_types: 'appointment.service_types',
    practitioner_services: 'appointment.practitioner_services',
    availability_rules: 'appointment.availability_rules',
    availability_exceptions: 'appointment.availability_exceptions',
    appointment_slots: 'appointment.appointment_slots',
    appointments: 'appointment.appointments',
    appointment_status_history: 'appointment.appointment_status_history',
    teleconsultation_sessions: 'appointment.teleconsultation_sessions',
    waiting_room_events: 'appointment.waiting_room_events',
  },
  diagnostics: {
    test_definitions: 'diagnostics.test_definitions',
    test_packages: 'diagnostics.test_packages',
    lab_providers: 'diagnostics.lab_providers',
    test_package_items: 'diagnostics.test_package_items',
    lab_locations: 'diagnostics.lab_locations',
    lab_offerings: 'diagnostics.lab_offerings',
    diagnostic_orders: 'diagnostics.diagnostic_orders',
    diagnostic_order_items: 'diagnostics.diagnostic_order_items',
    sample_collections: 'diagnostics.sample_collections',
    diagnostic_reports: 'diagnostics.diagnostic_reports',
    samples: 'diagnostics.samples',
    diagnostic_result_values: 'diagnostics.diagnostic_result_values',
    sample_events: 'diagnostics.sample_events',
  },
  pricing: {
    tax_rules: 'pricing.tax_rules',
    promotions: 'pricing.promotions',
    pricing_evaluations: 'pricing.pricing_evaluations',
    promotion_versions: 'pricing.promotion_versions',
    coupon_codes: 'pricing.coupon_codes',
    promotion_redemptions: 'pricing.promotion_redemptions',
    price_books: 'pricing.price_books',
    product_prices: 'pricing.product_prices',
  },
  marketplace: {
    commission_plans: 'marketplace.commission_plans',
    sellers: 'marketplace.sellers',
    seller_commission_assignments: 'marketplace.seller_commission_assignments',
    seller_ratings: 'marketplace.seller_ratings',
    seller_service_levels: 'marketplace.seller_service_levels',
    seller_locations: 'marketplace.seller_locations',
    seller_product_listings: 'marketplace.seller_product_listings',
  },
  commerce: {
    carts: 'commerce.carts',
    checkouts: 'commerce.checkouts',
    orders: 'commerce.orders',
    order_groups: 'commerce.order_groups',
    order_charges: 'commerce.order_charges',
    order_status_history: 'commerce.order_status_history',
    cancellations: 'commerce.cancellations',
    returns: 'commerce.returns',
    cart_items: 'commerce.cart_items',
    order_items: 'commerce.order_items',
    order_discounts: 'commerce.order_discounts',
    cancellation_items: 'commerce.cancellation_items',
    return_items: 'commerce.return_items',
    order_allocations: 'commerce.order_allocations',
  },
  payment: {
    provider_accounts: 'payment.provider_accounts',
    payment_webhooks: 'payment.payment_webhooks',
    customer_payment_methods: 'payment.customer_payment_methods',
    reconciliation_runs: 'payment.reconciliation_runs',
    reconciliation_items: 'payment.reconciliation_items',
    payment_intents: 'payment.payment_intents',
    payment_attempts: 'payment.payment_attempts',
    payment_transactions: 'payment.payment_transactions',
    refunds: 'payment.refunds',
    chargebacks: 'payment.chargebacks',
    cod_collections: 'payment.cod_collections',
  },
  finance: {
    accounts: 'finance.accounts',
    journal_entries: 'finance.journal_entries',
    journal_lines: 'finance.journal_lines',
    settlement_runs: 'finance.settlement_runs',
    invoices: 'finance.invoices',
    settlement_items: 'finance.settlement_items',
    invoice_items: 'finance.invoice_items',
    credit_notes: 'finance.credit_notes',
  },
  insurance: {
    insurers: 'insurance.insurers',
    tpas: 'insurance.tpas',
    policies: 'insurance.policies',
    policy_members: 'insurance.policy_members',
    eligibility_checks: 'insurance.eligibility_checks',
    claims: 'insurance.claims',
    claim_documents: 'insurance.claim_documents',
    claim_status_history: 'insurance.claim_status_history',
  },
  membership: {
    plans: 'membership.plans',
    plan_benefits: 'membership.plan_benefits',
    loyalty_accounts: 'membership.loyalty_accounts',
    subscriptions: 'membership.subscriptions',
    loyalty_ledger: 'membership.loyalty_ledger',
    benefit_usage: 'membership.benefit_usage',
  },
  procurement: {
    suppliers: 'procurement.suppliers',
    supplier_licenses: 'procurement.supplier_licenses',
    purchase_requisitions: 'procurement.purchase_requisitions',
    purchase_returns: 'procurement.purchase_returns',
    purchase_orders: 'procurement.purchase_orders',
    supplier_products: 'procurement.supplier_products',
    purchase_requisition_items: 'procurement.purchase_requisition_items',
    supplier_invoices: 'procurement.supplier_invoices',
    purchase_order_items: 'procurement.purchase_order_items',
    goods_receipts: 'procurement.goods_receipts',
    goods_receipt_items: 'procurement.goods_receipt_items',
    goods_receipt_quality_checks: 'procurement.goods_receipt_quality_checks',
    purchase_return_items: 'procurement.purchase_return_items',
  },
  warehouse: {
    warehouses: 'warehouse.warehouses',
    zones: 'warehouse.zones',
    inventory_adjustments: 'warehouse.inventory_adjustments',
    stock_transfers: 'warehouse.stock_transfers',
    aisles: 'warehouse.aisles',
    racks: 'warehouse.racks',
    replenishment_rules: 'warehouse.replenishment_rules',
    bins: 'warehouse.bins',
    cycle_counts: 'warehouse.cycle_counts',
    inventory_lots: 'warehouse.inventory_lots',
    stock_balances: 'warehouse.stock_balances',
    stock_ledger: 'warehouse.stock_ledger',
    stock_reservations: 'warehouse.stock_reservations',
    stock_holds: 'warehouse.stock_holds',
    inventory_adjustment_items: 'warehouse.inventory_adjustment_items',
    stock_transfer_items: 'warehouse.stock_transfer_items',
    cycle_count_items: 'warehouse.cycle_count_items',
  },
  fulfillment: {
    picking_waves: 'fulfillment.picking_waves',
    fulfillment_orders: 'fulfillment.fulfillment_orders',
    picking_wave_orders: 'fulfillment.picking_wave_orders',
    pick_tasks: 'fulfillment.pick_tasks',
    pack_tasks: 'fulfillment.pack_tasks',
    fulfillment_events: 'fulfillment.fulfillment_events',
    packages: 'fulfillment.packages',
    fulfillment_order_items: 'fulfillment.fulfillment_order_items',
    pick_task_items: 'fulfillment.pick_task_items',
    package_items: 'fulfillment.package_items',
  },
  logistics: {
    carriers: 'logistics.carriers',
    carrier_accounts: 'logistics.carrier_accounts',
    serviceability_rules: 'logistics.serviceability_rules',
    delivery_slots: 'logistics.delivery_slots',
    delivery_routes: 'logistics.delivery_routes',
    reverse_shipments: 'logistics.reverse_shipments',
    shipments: 'logistics.shipments',
    shipment_events: 'logistics.shipment_events',
    delivery_assignments: 'logistics.delivery_assignments',
    delivery_attempts: 'logistics.delivery_attempts',
    ndr_cases: 'logistics.ndr_cases',
  },
  notification: {
    templates: 'notification.templates',
    provider_configurations: 'notification.provider_configurations',
    provider_webhooks: 'notification.provider_webhooks',
    suppressions: 'notification.suppressions',
    messages: 'notification.messages',
    device_endpoints: 'notification.device_endpoints',
    user_channel_preferences: 'notification.user_channel_preferences',
    message_attachments: 'notification.message_attachments',
    message_attempts: 'notification.message_attempts',
    in_app_notifications: 'notification.in_app_notifications',
  },
  support: {
    sla_policies: 'support.sla_policies',
    ticket_tags: 'support.ticket_tags',
    tickets: 'support.tickets',
    ticket_messages: 'support.ticket_messages',
    ticket_actions: 'support.ticket_actions',
    ticket_status_history: 'support.ticket_status_history',
    ticket_tag_assignments: 'support.ticket_tag_assignments',
    ticket_attachments: 'support.ticket_attachments',
  },
  compliance: {
    regulatory_authorities: 'compliance.regulatory_authorities',
    legal_holds: 'compliance.legal_holds',
    privacy_requests: 'compliance.privacy_requests',
    regulatory_registrations: 'compliance.regulatory_registrations',
    evidence: 'compliance.evidence',
    product_recalls: 'compliance.product_recalls',
    adverse_event_reports: 'compliance.adverse_event_reports',
    recall_lots: 'compliance.recall_lots',
  },
  risk: {
    rules: 'risk.rules',
    assessments: 'risk.assessments',
    signals: 'risk.signals',
    cases: 'risk.cases',
    blocklists: 'risk.blocklists',
  },
  platform: {
    outbox_events: 'platform.outbox_events',
    inbox_messages: 'platform.inbox_messages',
    idempotency_keys: 'platform.idempotency_keys',
    feature_flags: 'platform.feature_flags',
    application_settings: 'platform.application_settings',
    data_retention_policies: 'platform.data_retention_policies',
    webhook_endpoints: 'platform.webhook_endpoints',
    scheduled_jobs: 'platform.scheduled_jobs',
    audit_logs: 'platform.audit_logs',
    file_objects: 'platform.file_objects',
    webhook_deliveries: 'platform.webhook_deliveries',
    file_upload_sessions: 'platform.file_upload_sessions',
    file_variants: 'platform.file_variants',
    file_access_grants: 'platform.file_access_grants',
    file_scan_events: 'platform.file_scan_events',
    file_access_events: 'platform.file_access_events',
  },
  search: {
    synonyms: 'search.synonyms',
    redirects: 'search.redirects',
    documents: 'search.documents',
    indexing_jobs: 'search.indexing_jobs',
    query_events: 'search.query_events',
  },
} as const;

export type DatabaseTable =
  | (typeof TABLES)['identity'][keyof (typeof TABLES)['identity']]
  | (typeof TABLES)['organization'][keyof (typeof TABLES)['organization']]
  | (typeof TABLES)['customer'][keyof (typeof TABLES)['customer']]
  | (typeof TABLES)['catalog'][keyof (typeof TABLES)['catalog']]
  | (typeof TABLES)['clinical'][keyof (typeof TABLES)['clinical']]
  | (typeof TABLES)['appointment'][keyof (typeof TABLES)['appointment']]
  | (typeof TABLES)['diagnostics'][keyof (typeof TABLES)['diagnostics']]
  | (typeof TABLES)['pricing'][keyof (typeof TABLES)['pricing']]
  | (typeof TABLES)['marketplace'][keyof (typeof TABLES)['marketplace']]
  | (typeof TABLES)['commerce'][keyof (typeof TABLES)['commerce']]
  | (typeof TABLES)['payment'][keyof (typeof TABLES)['payment']]
  | (typeof TABLES)['finance'][keyof (typeof TABLES)['finance']]
  | (typeof TABLES)['insurance'][keyof (typeof TABLES)['insurance']]
  | (typeof TABLES)['membership'][keyof (typeof TABLES)['membership']]
  | (typeof TABLES)['procurement'][keyof (typeof TABLES)['procurement']]
  | (typeof TABLES)['warehouse'][keyof (typeof TABLES)['warehouse']]
  | (typeof TABLES)['fulfillment'][keyof (typeof TABLES)['fulfillment']]
  | (typeof TABLES)['logistics'][keyof (typeof TABLES)['logistics']]
  | (typeof TABLES)['notification'][keyof (typeof TABLES)['notification']]
  | (typeof TABLES)['support'][keyof (typeof TABLES)['support']]
  | (typeof TABLES)['compliance'][keyof (typeof TABLES)['compliance']]
  | (typeof TABLES)['risk'][keyof (typeof TABLES)['risk']]
  | (typeof TABLES)['platform'][keyof (typeof TABLES)['platform']]
  | (typeof TABLES)['search'][keyof (typeof TABLES)['search']];

export type TableSchema = keyof typeof TABLES;
