packages:
  - apps/*
  - libs/*
  - libs/platform/*
  - libs/modules/*
allowBuilds:
  '@parcel/watcher': set this to true or false
  '@scarf/scarf': set this to true or false
  unrs-resolver: set this to true or false
