/**
 * Reusable OpenAPI decorators for auth endpoints.
 * Used backward by auth controllers; connects forward to Swagger's security, header, and response metadata.
 */
import { applyDecorators, type Type } from '@nestjs/common';
import {
  ApiBadRequestResponse,
  ApiBearerAuth,
  ApiBody,
  ApiConflictResponse,
  ApiForbiddenResponse,
  ApiHeader,
  ApiInternalServerErrorResponse,
  ApiNotFoundResponse,
  ApiOperation,
  ApiParam,
  ApiQuery,
  ApiResponse,
  ApiServiceUnavailableResponse,
  ApiUnauthorizedResponse,
} from '@nestjs/swagger';

const errorExample = {
  success: false,
  message: 'The request could not be completed.',
  data: null,
  error: { code: 'HTTP_ERROR', details: null },
  meta: {
    requestId: 'request-id',
    correlationId: 'correlation-id',
    apiVersion: 'v1',
    timestamp: '2026-01-01T00:00:00.000Z',
  },
};

/** Describe a protected endpoint and its required bearer header in one place. */
export function ApiProtected(): MethodDecorator & ClassDecorator {
  return applyDecorators(
    ApiBearerAuth(),
    ApiHeader({
      name: 'Authorization',
      required: true,
      description: 'Access token issued by login, registration, or token refresh.',
      schema: { type: 'string', example: 'Bearer eyJhbGciOiJIUzI1NiIs...' },
    }),
    ApiUnauthorizedResponse({
      description: 'The access token is missing, invalid, expired, or revoked.',
      schema: {
        example: { ...errorExample, error: { code: 'AUTHENTICATION_REQUIRED', details: null } },
      },
    }),
  );
}

/** Document the optional device context consumed when a session is created. */
export function ApiClientContextHeaders(): MethodDecorator {
  return applyDecorators(
    ApiHeader({
      name: 'X-Device-Id',
      required: false,
      description: 'Stable client/device identifier used for session tracking.',
      schema: { type: 'string', example: 'android-pixel-8a-01' },
    }),
    ApiHeader({
      name: 'X-Device-Type',
      required: false,
      description: 'Client platform recorded with the session.',
      schema: { type: 'string', enum: ['android', 'ios', 'web'], example: 'android' },
    }),
  );
}

/** Add the common validation response generated by the global ValidationPipe. */
export function ApiValidationError(): MethodDecorator {
  return ApiBadRequestResponse({
    description: 'The request body, query, or path parameter failed validation.',
    schema: { example: errorExample },
  });
}

/** Add the standard response envelope used by ApiResponseInterceptor. */
export function ApiAuthResponse(
  description: string,
  dataExample: unknown,
  status = 200,
): MethodDecorator {
  return ApiResponse({
    status,
    description,
    schema: {
      example: {
        success: true,
        message: 'Operation completed successfully.',
        data: dataExample,
        error: null,
        meta: {
          requestId: 'request-id',
          correlationId: 'correlation-id',
          apiVersion: 'v1',
          timestamp: '2026-01-01T00:00:00.000Z',
        },
      },
    },
  });
}

/** Document a request body while keeping the controller method's DTO type as the source of truth. */
export function ApiAuthBody(type: Type<unknown>, description: string): MethodDecorator {
  return ApiBody({ type, description });
}

/** Add common protected-resource failures for administrative endpoints. */
export function ApiProtectedErrors(): MethodDecorator & ClassDecorator {
  return applyDecorators(
    ApiForbiddenResponse({
      description: 'The authenticated user lacks the required permission.',
      schema: {
        example: { ...errorExample, error: { code: 'PERMISSION_DENIED', details: null } },
      },
    }),
    ApiNotFoundResponse({
      description: 'The requested auth resource was not found.',
      schema: {
        example: { ...errorExample, error: { code: 'RESOURCE_NOT_FOUND', details: null } },
      },
    }),
    ApiConflictResponse({
      description: 'The requested change conflicts with existing auth state.',
      schema: { example: { ...errorExample, error: { code: 'RESOURCE_CONFLICT', details: null } } },
    }),
    ApiInternalServerErrorResponse({
      description: 'An unexpected infrastructure failure occurred.',
      schema: {
        example: { ...errorExample, error: { code: 'INTERNAL_SERVER_ERROR', details: null } },
      },
    }),
    ApiServiceUnavailableResponse({
      description: 'A required database or infrastructure dependency is temporarily unavailable.',
      schema: {
        example: { ...errorExample, error: { code: 'DATABASE_ERROR', details: null } },
      },
    }),
  );
}

/** Document a UUID path parameter validated by ParseUUIDPipe. */
export function ApiAuthUuidParam(name: string, description: string): MethodDecorator {
  return ApiParam({
    name,
    required: true,
    description,
    format: 'uuid',
    example: '550e8400-e29b-41d4-a716-446655440000',
  });
}

/** Document a query DTO validated by the global ValidationPipe. */
export function ApiAuthQuery(type: Type<unknown>, description: string): MethodDecorator {
  return ApiQuery({ type, description });
}

/** Apply a concise operation summary and explanation. */
export function ApiAuthOperation(summary: string, description: string): MethodDecorator {
  return ApiOperation({ summary, description });
}
