// * Provides HTTP request context, response formatting, and exception handling for the application.
// * Used by modules and application bootstrap code through the platform public API.
export {
  AppError,
  ApplicationError,
  AuthenticationError,
  InvalidCredentialsError,
  OtpAlreadyUsedError,
  OtpAttemptsExceededError,
  OtpExpiredError,
  OtpInvalidError,
  AuthorizationError,
  ConflictError,
  DatabaseError,
  DomainError,
  ExternalServiceError,
  ExternalServiceTimeoutError,
  InfrastructureError,
  InfrastructureUnavailableError,
  NotFoundError,
  OperationTimeoutError,
  RefreshTokenReuseError,
  SessionRevokedError,
  ValidationError,
} from '@shared/errors';
